name: Terraform Apply

permissions:
  id-token: write
# Only run this workflow on commits to the main branch
on:
  push:
    branches:
      - 'main'
      - 'ch6'
jobs:
  TerraformApply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Authenticate to AWS using OIDC
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          # Specify the IAM role to assume here
          role-to-assume: arn:aws:iam::123456789012:role/example-role
          aws-region: us-west-2

      # Run Terraform using HashiCorp's setup-terraform Action
      - uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.1.0
            terraform_wrapper: false
        run: |
            terraform init
            terraform apply -auto-approve